### ISSUE TITLE
Obsolete

### ISSUE THREAD

**Issue by barbm2020** [imasm/wpfkb#2]
WpfKb is effectively obsolete.  It is based upon System.Windows.Interativity.  This has been abandoned by Microsoft and no longer has any type of support.  An effort was made to replace it by Microsoft.Xaml.Behaviors.Wpf (https://github.com/microsoft/XamlBehaviorsWpf)  This effort has flounder due to lack of interest on Microsoft's part (https://github.com/PrismLibrary/Prism/issues/1804)

**Comment by imasm** [comment]
Hi, thanks four your comment.  I've just created [NET48](https://github.com/imasm/wpfkb/tree/net48) and [NET6](https://github.com/imasm/wpfkb/tree/net60) versions that uses XamlBehaviors for WPF.

This library continues to be used in PrismLibrary so I thinki t's still good replacement for System.Windows.Interativity.
